server:   
  port: 7001  
      
eureka:  
  instance:
    hostname: localhost
    prefer-ip-address: true
  client:   
    registerWithEureka: false  
    fetchRegistry: false  
    serviceUrl:   
      defaultZone: http://localhost:7001/eureka/  